choco install -y chocolatey
choco install -y git
choco install -y notepadplusplus
choco install -y googlechrome
choco install -y brave
choco install -y nodejs
choco install -y 7zip
choco install -y visualstudiocode
choco install -y azurepowershell
choco install -y visualstudio2022enterprise
choco install -y visualstudio2022-workload-azure
choco install -y visualstudio2022-workload-netcoretools
choco install -y visualstudio2022-workload-netweb
choco install -y sql-server-management-studio
choco install -y docker-cli
choco install -y docker-engine
choco install -y postman
choco install -y dotnetcore-sdk
choco install -y firacode
choco install -y microsoftazurestorageexplorer
choco install -y servicebusexplorer
choco install -y spotify
choco install -y nswagstudio
