choco install -y chocolatey
choco install -y git
choco install -y notepadplusplus
choco install -y googlechrome
choco install -y nodejs
choco install -y 7zip
choco install -y putty
choco install -y paint.net
choco install -y visualstudiocode
choco install -y azurepowershell
choco install -y visualstudio2017enterprise
choco install -y visualstudio2017-workload-azure
choco install -y visualstudio2017-workload-netcoretools
choco install -y visualstudio2017-workload-netweb
choco install -y visualstudio2017-workload-netcrossplat
choco install -y sql-server-management-studio
choco install -y docker-for-windows
choco install -y slack
choco install -y everything
choco install -y wox
choco install -y resharper-ultimate-all
choco install -y postman
choco install -y prefix
choco install -y sandcastle
choco install -y sourcetree
choco install -y dotnetcore-sdk
choco install -y firacode
choco install -y microsoftazurestorageexplorer
